import { ThemeProvider } from "@/components/theme/theme-provider";
import GridPattern from "@/components/ui/grid-pattern";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { DesktopNav } from "@/components/desktop-nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const machina = localFont({
  src: "./fonts/NeueMachina-Ultrabold.otf",
  variable: "--font-machina",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
            className={cn(`${geistSans.variable} ${machina.variable}` , "antialiased font-[family-name:var(--font-geist-sans)] lg:max-w-[1200px] mx-auto") }
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GridPattern
                 width={100}
                 height={100}
                 x={-1}
                 y={-1}
                 className={cn( "lg:max-w-[1200.5px] border border-[#555555] border-opacity-25 mx-auto -z-50" )}
        /> <DesktopNav />
            {children}

          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
